### ISSUE TITLE
UX "tags" and automated workflow in github

### ISSUE THREAD

**Issue by sorensensig** [digdir/user-experience#1]
## Need
To ensure that we're truly building human-centred experiences and good quality products, we must better align our UX activities. 

## Opportunity
Align UX activities across the organisation for better strategic product decisions and UX planning across teams.

## Potential Solution
One way to achieve better alignment is to establish a joint view of UX deliveries across all teams and repositories. Github projects can be used to gain a better overview of issues across repositories. However, using multiple project boards will quickly ramp up manual work tied to tracking issues and updating status. Using Github's built in workflows alongside one set of labels for UX can help us automate the majority of work related to adding and tracking issues.

**Tags**
- ux
All issues that relates to user experience are tagged with the UX tag.

- ♿️ accessibility
Issues related to WCAG and Accessibility.

- 🔁 product-consistency
Issues that require consistency validation within or across products.

- 🔤 content
Issues that require text or other content design.

Some of these labels overlap with labels used by teams and other disciplines on purpose and will "hopefully" not change their current use of said labels. However, in for example pairing the triage label with the ux label, it becomes apparent that there is a ux element to evaluating the urgency of said issue.

## Github workflow

**add-issue-to-project-by-label.yml**
```github.com/orgs/digdir/.github/.github/workflows/automation```
```
name: Add issue to project by label

on:
    workflow_call:
        secrets:
            token:
                required: false

jobs:
    add_issue_to_project:
        name: Add issue to project
        runs-on: ubuntu-latest
        steps:
            - name: UX
              uses: actions/add-to-project@v1.0.2
              with:
                project-url: https://github.com/orgs/digdir/projects/25
                github-token: ${{ secrets.ux_project_token }}
                labeled: ux, ♿️ accessibility, 🔁 product-consistency, 🔤 content
                label-operator: OR
```

**add-issue-to-project-by-label.properties.json**
```github.com/orgs/digdir/.github/.github/workflows/automation/properties```
```
{
  "name": "Add to project",
  "description": "Adds issue to cross-team project based on label",
  "iconName": "octicon project-symlink",
  "categories": " ["Automation"]"
}
```

**handle-label-events.yml**
```github.com/orgs/digdir/<relevant repository>/.github/workflows```
```
name: On issue labeled
on:
  issues:
    types: [labeled]

jobs:
  name: Call workflow - add issue to project by label
    uses: digdir/.github/.github/workflows/automation/add-issue-to-project-by-label.yml@main
    secrets: inherit
```
